---
- name: Get tables in Namespace
  ansible.builtin.uri:
    url: "{{ plf_api_base_url }}/api/catalog/v1/{{ plf_catalog_name }}/namespaces/{{ item }}/tables"
    method: GET
    headers:
      Authorization: "Bearer {{ plf_access_token }}"
      Accept: application/json
      Content-Type: application/json
      Polaris-Realm: "{{ plf_realm }}"
    status_code:
      - 200
  register: table_response
  tags:
    - cleanup

- name: Print table
  ansible.builtin.debug:
    var: table_response
  tags:
    - debug

- name: Drop Table in Namespace
  ansible.builtin.uri:
    url: "{{ plf_api_base_url }}/api/catalog/v1/{{ plf_catalog_name }}/namespaces/{{ item
      }}/tables/{{ item_table.name }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ plf_access_token }}"
      Polaris-Realm: "{{ plf_realm }}"
    status_code:
      - 204
      - 404
  loop: "{{ table_response.json.identifiers }}"
  loop_control:
    label: "{{ item_table.name }}"
    loop_var: item_table
  tags:
    - cleanup

- name: Delete the namespace in catalog {{ item }}
  ansible.builtin.uri:
    url: "{{ plf_api_base_url }}/api/catalog/v1/{{ plf_catalog_name }}/namespaces/{{ item }}"
    method: DELETE
    headers: "{{ plf_default_headers }}"
    status_code: [204, 404]
  tags:
    - cleanup
