apiVersion: apps/v1
kind: Deployment
metadata:
  name: polaris
spec:
  selector:
    matchLabels:
      app: polaris
  template:
    metadata:
      labels:
        app: polaris
    spec:
      serviceAccountName: polaris
      containers:
        - name: polaris
          image: ghcr.io/snowflake-labs/polaris-local-forge/apache-polaris-server-pgsql
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: polaris-properties
          resources:
            requests:
              memory: "1024Mi"
              cpu: "500m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8181
            - containerPort: 8282
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8182
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 10
            terminationGracePeriodSeconds: 10
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8182
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 30
          volumeMounts:
            - name: persistence-config
              readOnly: true
              mountPath: /polaris/config
            - name: polaris-credentials
              readOnly: true
              mountPath: /polaris/credentials
      volumes:
        - name: persistence-config
          configMap:
            name: persistence-config
        - name: polaris-credentials
          secret:
            secretName: polaris-credentials
